name: Newai Prime Final Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create Requirements File
        run: |
          echo "flet" > requirements.txt
          echo "groq" >> requirements.txt

      - name: Install Dependencies
        run: |
          pip install flet groq

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: flet build apk --org "com.sametcan88" --product "Newai Prime" --build-number 2 --build-version 2.0.1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Newai-Prime-APK
          path: build/apk/*.apk
